# Generated by Django 4.2.3 on 2023-08-06 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snacks', '0002_rename_desc_snack_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anything', models.CharField(max_length=255)),
            ],
        ),
    ]
